/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StreetsRouteImport } from './routes/streets'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiCompanySiteRouteImport } from './routes/api/company-site'
import { Route as ApiNotionSetupRouteImport } from './routes/api/notion-setup'
import { Route as ApiNotionSyncRouteImport } from './routes/api/notion-sync'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiStreetsRouteImport } from './routes/api/streets'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiWeatherPulseRouteImport } from './routes/api/weather-pulse'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachCardsRouteImport } from './routes/coach.cards'
import { Route as CoachInspectRouteImport } from './routes/coach.inspect'
import { Route as CoachMindsetRouteImport } from './routes/coach.mindset'
import { Route as CoachReferenceRouteImport } from './routes/coach.reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StreetsRoute = StreetsRouteImport.update({
  id: '/streets',
  path: '/streets',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanySiteRoute = ApiCompanySiteRouteImport.update({
  id: '/api/company-site',
  path: '/api/company-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionSetupRoute = ApiNotionSetupRouteImport.update({
  id: '/api/notion-setup',
  path: '/api/notion-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionSyncRoute = ApiNotionSyncRouteImport.update({
  id: '/api/notion-sync',
  path: '/api/notion-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreetsRoute = ApiStreetsRouteImport.update({
  id: '/api/streets',
  path: '/api/streets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherPulseRoute = ApiWeatherPulseRouteImport.update({
  id: '/api/weather-pulse',
  path: '/api/weather-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCardsRoute = CoachCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => CoachRoute,
} as any)
const CoachInspectRoute = CoachInspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => CoachRoute,
} as any)
const CoachMindsetRoute = CoachMindsetRouteImport.update({
  id: '/mindset',
  path: '/mindset',
  getParentRoute: () => CoachRoute,
} as any)
const CoachReferenceRoute = CoachReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/settings': typeof SettingsRoute
  '/streets': typeof StreetsRoute
  '/today': typeof TodayRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/company-site': typeof ApiCompanySiteRoute
  '/api/notion-setup': typeof ApiNotionSetupRoute
  '/api/notion-sync': typeof ApiNotionSyncRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/streets': typeof ApiStreetsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/weather-pulse': typeof ApiWeatherPulseRoute
  '/coach/cards': typeof CoachCardsRoute
  '/coach/inspect': typeof CoachInspectRoute
  '/coach/mindset': typeof CoachMindsetRoute
  '/coach/reference': typeof CoachReferenceRoute
  '/coach/': typeof CoachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/streets': typeof StreetsRoute
  '/today': typeof TodayRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/company-site': typeof ApiCompanySiteRoute
  '/api/notion-setup': typeof ApiNotionSetupRoute
  '/api/notion-sync': typeof ApiNotionSyncRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/streets': typeof ApiStreetsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/weather-pulse': typeof ApiWeatherPulseRoute
  '/coach/cards': typeof CoachCardsRoute
  '/coach/inspect': typeof CoachInspectRoute
  '/coach/mindset': typeof CoachMindsetRoute
  '/coach/reference': typeof CoachReferenceRoute
  '/coach': typeof CoachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/settings': typeof SettingsRoute
  '/streets': typeof StreetsRoute
  '/today': typeof TodayRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/company-site': typeof ApiCompanySiteRoute
  '/api/notion-setup': typeof ApiNotionSetupRoute
  '/api/notion-sync': typeof ApiNotionSyncRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/streets': typeof ApiStreetsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/weather-pulse': typeof ApiWeatherPulseRoute
  '/coach/cards': typeof CoachCardsRoute
  '/coach/inspect': typeof CoachInspectRoute
  '/coach/mindset': typeof CoachMindsetRoute
  '/coach/reference': typeof CoachReferenceRoute
  '/coach/': typeof CoachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/settings'
    | '/streets'
    | '/today'
    | '/api/coach'
    | '/api/company-site'
    | '/api/notion-setup'
    | '/api/notion-sync'
    | '/api/speech'
    | '/api/streets'
    | '/api/transcribe'
    | '/api/weather'
    | '/api/weather-pulse'
    | '/coach/cards'
    | '/coach/inspect'
    | '/coach/mindset'
    | '/coach/reference'
    | '/coach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/streets'
    | '/today'
    | '/api/coach'
    | '/api/company-site'
    | '/api/notion-setup'
    | '/api/notion-sync'
    | '/api/speech'
    | '/api/streets'
    | '/api/transcribe'
    | '/api/weather'
    | '/api/weather-pulse'
    | '/coach/cards'
    | '/coach/inspect'
    | '/coach/mindset'
    | '/coach/reference'
    | '/coach'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/settings'
    | '/streets'
    | '/today'
    | '/api/coach'
    | '/api/company-site'
    | '/api/notion-setup'
    | '/api/notion-sync'
    | '/api/speech'
    | '/api/streets'
    | '/api/transcribe'
    | '/api/weather'
    | '/api/weather-pulse'
    | '/coach/cards'
    | '/coach/inspect'
    | '/coach/mindset'
    | '/coach/reference'
    | '/coach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StreetsRoute: typeof StreetsRoute
  TodayRoute: typeof TodayRoute
  ApiCoachRoute: typeof ApiCoachRoute
  ApiCompanySiteRoute: typeof ApiCompanySiteRoute
  ApiNotionSetupRoute: typeof ApiNotionSetupRoute
  ApiNotionSyncRoute: typeof ApiNotionSyncRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiStreetsRoute: typeof ApiStreetsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  ApiWeatherPulseRoute: typeof ApiWeatherPulseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streets': {
      id: '/streets'
      path: '/streets'
      fullPath: '/streets'
      preLoaderRoute: typeof StreetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-site': {
      id: '/api/company-site'
      path: '/api/company-site'
      fullPath: '/api/company-site'
      preLoaderRoute: typeof ApiCompanySiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion-setup': {
      id: '/api/notion-setup'
      path: '/api/notion-setup'
      fullPath: '/api/notion-setup'
      preLoaderRoute: typeof ApiNotionSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion-sync': {
      id: '/api/notion-sync'
      path: '/api/notion-sync'
      fullPath: '/api/notion-sync'
      preLoaderRoute: typeof ApiNotionSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streets': {
      id: '/api/streets'
      path: '/api/streets'
      fullPath: '/api/streets'
      preLoaderRoute: typeof ApiStreetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather-pulse': {
      id: '/api/weather-pulse'
      path: '/api/weather-pulse'
      fullPath: '/api/weather-pulse'
      preLoaderRoute: typeof ApiWeatherPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/cards': {
      id: '/coach/cards'
      path: '/cards'
      fullPath: '/coach/cards'
      preLoaderRoute: typeof CoachCardsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/inspect': {
      id: '/coach/inspect'
      path: '/inspect'
      fullPath: '/coach/inspect'
      preLoaderRoute: typeof CoachInspectRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/mindset': {
      id: '/coach/mindset'
      path: '/mindset'
      fullPath: '/coach/mindset'
      preLoaderRoute: typeof CoachMindsetRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/reference': {
      id: '/coach/reference'
      path: '/reference'
      fullPath: '/coach/reference'
      preLoaderRoute: typeof CoachReferenceRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface CoachRouteChildren {
  CoachCardsRoute: typeof CoachCardsRoute
  CoachInspectRoute: typeof CoachInspectRoute
  CoachMindsetRoute: typeof CoachMindsetRoute
  CoachReferenceRoute: typeof CoachReferenceRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachCardsRoute: CoachCardsRoute,
  CoachInspectRoute: CoachInspectRoute,
  CoachMindsetRoute: CoachMindsetRoute,
  CoachReferenceRoute: CoachReferenceRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StreetsRoute: StreetsRoute,
  TodayRoute: TodayRoute,
  ApiCoachRoute: ApiCoachRoute,
  ApiCompanySiteRoute: ApiCompanySiteRoute,
  ApiNotionSetupRoute: ApiNotionSetupRoute,
  ApiNotionSyncRoute: ApiNotionSyncRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiStreetsRoute: ApiStreetsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  ApiWeatherPulseRoute: ApiWeatherPulseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
