/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachInspectRouteImport } from './routes/coach.inspect'
import { Route as CoachMindsetRouteImport } from './routes/coach.mindset'
import { Route as CoachReferenceRouteImport } from './routes/coach.reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachInspectRoute = CoachInspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => CoachRoute,
} as any)
const CoachMindsetRoute = CoachMindsetRouteImport.update({
  id: '/mindset',
  path: '/mindset',
  getParentRoute: () => CoachRoute,
} as any)
const CoachReferenceRoute = CoachReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/settings': typeof SettingsRoute
  '/api/coach': typeof ApiCoachRoute
  '/coach/inspect': typeof CoachInspectRoute
  '/coach/mindset': typeof CoachMindsetRoute
  '/coach/reference': typeof CoachReferenceRoute
  '/coach/': typeof CoachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/coach': typeof ApiCoachRoute
  '/coach/inspect': typeof CoachInspectRoute
  '/coach/mindset': typeof CoachMindsetRoute
  '/coach/reference': typeof CoachReferenceRoute
  '/coach': typeof CoachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/settings': typeof SettingsRoute
  '/api/coach': typeof ApiCoachRoute
  '/coach/inspect': typeof CoachInspectRoute
  '/coach/mindset': typeof CoachMindsetRoute
  '/coach/reference': typeof CoachReferenceRoute
  '/coach/': typeof CoachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/settings'
    | '/api/coach'
    | '/coach/inspect'
    | '/coach/mindset'
    | '/coach/reference'
    | '/coach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/coach'
    | '/coach/inspect'
    | '/coach/mindset'
    | '/coach/reference'
    | '/coach'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/settings'
    | '/api/coach'
    | '/coach/inspect'
    | '/coach/mindset'
    | '/coach/reference'
    | '/coach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ApiCoachRoute: typeof ApiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/inspect': {
      id: '/coach/inspect'
      path: '/inspect'
      fullPath: '/coach/inspect'
      preLoaderRoute: typeof CoachInspectRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/mindset': {
      id: '/coach/mindset'
      path: '/mindset'
      fullPath: '/coach/mindset'
      preLoaderRoute: typeof CoachMindsetRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/reference': {
      id: '/coach/reference'
      path: '/reference'
      fullPath: '/coach/reference'
      preLoaderRoute: typeof CoachReferenceRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface CoachRouteChildren {
  CoachInspectRoute: typeof CoachInspectRoute
  CoachMindsetRoute: typeof CoachMindsetRoute
  CoachReferenceRoute: typeof CoachReferenceRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachInspectRoute: CoachInspectRoute,
  CoachMindsetRoute: CoachMindsetRoute,
  CoachReferenceRoute: CoachReferenceRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ApiCoachRoute: ApiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
